# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_auto_20160419_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='reade',
            field=models.BooleanField(default=0, verbose_name='\u662f\u5426\u5df2\u8bfb'),
        ),
    ]
