# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_notify_reade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='reade',
            new_name='read',
        ),
    ]
