# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_auto_20160419_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6d88\u606f\u83b7\u53d6\u65f6\u95f4'),
        ),
    ]
